Update workflows with test result reporting

diff --git a/.github/workflows/java_ci.yml b/.github/workflows/java_ci.yml
--- a/.github/workflows/java_ci.yml
+++ b/.github/workflows/java_ci.yml
@@ -19,9 +19,14 @@ jobs:
           java-version: '16'
           distribution: 'temurin'
       - name: Build with Gradle
-        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
+        uses: gradle/gradle-build-action@v2
         with:
           arguments: build test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
       - name: Query Version
         run: |
           echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
